name: Aspect Workflows
description: |
  Delivers the promised 10x performance benefit of Bazel.
  Auto-scaling "warm" runners, remote cache & exec, CD and more.
branding:
  icon: triangle
  color: gray-dark
inputs:
  workspace:
    description: path from the git repository to the WORKSPACE.bazel file
    required: true
    default: '.'
  task:
    description: the task that we want to generate steps for and then run
    required: true
  args:
    description: additional arguments to be passed to the task instance
    required: false
    default: ''

runs:
  # Declare this is a "Composite Action"
  using: 'node20'
  main: 'index.js'
